Repository container-mgmt/dedicated-portal, pull requests merged in 2018-07, with the labels that each got.

#80 Do not crash on user input while serving http request
  cmd/customers-service/handlers.go
  cmd/customers-service/sql_customers_service_test.go
Labels: bug

#56 Add a swagger codegen test
  cmd/customers-service/customers-service.yaml
  cmd/customers-service/swagger/README.adoc
  cmd/customers-service/swagger/swagger_test.py
Labels: ci

#83 Check token
  Gopkg.lock
  Gopkg.toml
  cmd/customers-service/handlers.go
  cmd/customers-service/jwtcert/jwtcert.go
  cmd/customers-service/server.go
  template.yml
Labels: enhancement

#88 Fix err eq nil typo
  cmd/customers-service/handlers.go
Labels: bug

#90 Add missing equal sign
  template.yml
Labels: bug

#91 Return the error creating cluster to the user
  cmd/clusters-service/handlers.go
Labels: enhancement

#96 Add demo mode option
  cmd/customers-service/README.adoc
  cmd/customers-service/handlers.go
  cmd/customers-service/models/customers.sql
  cmd/customers-service/server.go
  cmd/customers-service/service/customer.go
  cmd/customers-service/service/customers_list.go
  cmd/customers-service/service/customers_service.go
  cmd/customers-service/service/demo_customers_service.go
  cmd/customers-service/service/sql_customers_service.go
  cmd/customers-service/service/sql_customers_service_test.go
  cmd/customers-service/swagger/customers-service.yaml
  cmd/customers-service/swagger/swagger_test.py
Labels: enhancement

#97 Check user id before answering requests
  cmd/customers-service/handlers.go
  cmd/customers-service/server.go
  cmd/customers-service/service/sql_customers_service.go
  pkg/auth/auth.go
Labels: enhancement

#101 Use migrations
  cmd/clusters-service/server.go
  cmd/customers-service/models/customers.sql
  cmd/customers-service/server.go
  cmd/customers-service/service/demo_customers_service.go
  images/customers-service/Dockerfile
  images/customers-service/migrations/1530102671_create_schema.down.sql
  images/customers-service/migrations/1530102671_create_schema.up.sql
  pkg/sql/schema.go
  template.yml
Labels: enhancement

#104 clusters-service: switch from env vars to flags broke deployment
  template.yml
Labels: bug

#94 Adding ClusterDeployment using cluster-operator
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  cmd/clusters-service/README.adoc
  cmd/clusters-service/cluster_provisioner.go
  cmd/clusters-service/clusters_service.go
  cmd/clusters-service/server.go
Labels: enhancement

#115 Refactor some code in customers service
  cmd/customers-service/handlers.go
  cmd/customers-service/server.go
  cmd/customers-service/service/demo_customers_service.go
  cmd/customers-service/service/sql_customers_service.go
  cmd/customers-service/service/sql_customers_service_test.go
Labels: code cleanup, size/XS

#116 Remove goimports check
  Makefile
  cmd/clusters-service/clusters_service.go
  hack/verify.sh
Labels: bug, ci
